#
#schemaName: sharding_db
#
#dataSourceCommon:
#  username: root
#  password:
#  connectionTimeoutMilliseconds: 30000
#  idleTimeoutMilliseconds: 60000
#  maxLifetimeMilliseconds: 1800000
#  maxPoolSize: 50
#  minPoolSize: 1
#  maintenanceIntervalMilliseconds: 30000

#dataSources:
#  ds:
#    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
#  shadow_ds:
#    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
#
#rules:
#- !SHADOW
#  column: shadow
#  sourceDataSourceNames:
#   - ds
#  shadowDataSourceNames:
#   - shadow_dsConfigCenter